import Head from 'next/head'
import { useEffect } from 'react'

export default function Home() {
  useEffect(() => {
    location.href = 'https://twitter.com/haruya_enmarke'
  })

  return (
    <>
      <Head>
        <title>リダイレクト中</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
